version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
